//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.CustomResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EauditResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EauditResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aisger.CustomResources.EauditResource", typeof(EauditResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое значение.
        /// </summary>
        public static string ActualValue {
            get {
                return ResourceManager.GetString("ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование расчетных параметров.
        /// </summary>
        public static string BuildingForm1Column1 {
            get {
                return ResourceManager.GetString("BuildingForm1Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование расчетных параметров.
        /// </summary>
        public static string BuildingForm1Column2 {
            get {
                return ResourceManager.GetString("BuildingForm1Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обозначение параметра.
        /// </summary>
        public static string BuildingForm1Column3 {
            get {
                return ResourceManager.GetString("BuildingForm1Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетное значение.
        /// </summary>
        public static string BuildingForm1Column5 {
            get {
                return ResourceManager.GetString("BuildingForm1Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетные условия.
        /// </summary>
        public static string BuildingForm1Name {
            get {
                return ResourceManager.GetString("BuildingForm1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели геометрические.
        /// </summary>
        public static string BuildingForm2Name {
            get {
                return ResourceManager.GetString("BuildingForm2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели теплотехнические.
        /// </summary>
        public static string BuildingForm3Name {
            get {
                return ResourceManager.GetString("BuildingForm3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели вспомогательные.
        /// </summary>
        public static string BuildingForm4Name {
            get {
                return ResourceManager.GetString("BuildingForm4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельные характеристики.
        /// </summary>
        public static string BuildingForm5Name {
            get {
                return ResourceManager.GetString("BuildingForm5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициенты.
        /// </summary>
        public static string BuildingForm6Name {
            get {
                return ResourceManager.GetString("BuildingForm6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комплексные показатели энергоэффективности.
        /// </summary>
        public static string BuildingForm7Name {
            get {
                return ResourceManager.GetString("BuildingForm7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБЪЕКТІ.
        /// </summary>
        public static string BuildingForm8Column1 {
            get {
                return ResourceManager.GetString("BuildingForm8Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое теплопотребление объекта.
        /// </summary>
        public static string BuildingForm8Column10 {
            get {
                return ResourceManager.GetString("BuildingForm8Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАКАЗЧИК.
        /// </summary>
        public static string BuildingForm8Column2 {
            get {
                return ResourceManager.GetString("BuildingForm8Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АДРЕС ОБЪЕКТА.
        /// </summary>
        public static string BuildingForm8Column3 {
            get {
                return ResourceManager.GetString("BuildingForm8Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОД ПОСТРОЙКИ.
        /// </summary>
        public static string BuildingForm8Column4 {
            get {
                return ResourceManager.GetString("BuildingForm8Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТИП.
        /// </summary>
        public static string BuildingForm8Column5 {
            get {
                return ResourceManager.GetString("BuildingForm8Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭТАЖНОСТЬ.
        /// </summary>
        public static string BuildingForm8Column51 {
            get {
                return ResourceManager.GetString("BuildingForm8Column51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБЩАЯ ПЛОЩАДЬ, м2.
        /// </summary>
        public static string BuildingForm8Column6 {
            get {
                return ResourceManager.GetString("BuildingForm8Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТАПЛИВАЕМАЯ ПЛОЩАДЬ, м2.
        /// </summary>
        public static string BuildingForm8Column7 {
            get {
                return ResourceManager.GetString("BuildingForm8Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРИСВОЕННЫЙ КЛАСС ЭНЕРГОЭФФЕКТИВНОСТИ.
        /// </summary>
        public static string BuildingForm8Column8 {
            get {
                return ResourceManager.GetString("BuildingForm8Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормативное теплопотребление объекта *.
        /// </summary>
        public static string BuildingForm8Column9 {
            get {
                return ResourceManager.GetString("BuildingForm8Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатель класса энергоэффективности здания..
        /// </summary>
        public static string BuildingForm8Name {
            get {
                return ResourceManager.GetString("BuildingForm8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Нормативные требования по теплопотреблению установлены для данного типа здания, согласно СН РК 2.04-04-2011 Тепловая защита зданий.
        /// </summary>
        public static string BuildingForm8SubText {
            get {
                return ResourceManager.GetString("BuildingForm8SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обозначения.
        /// </summary>
        public static string BuildingForm9Column3 {
            get {
                return ResourceManager.GetString("BuildingForm9Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величина.
        /// </summary>
        public static string BuildingForm9Column5 {
            get {
                return ResourceManager.GetString("BuildingForm9Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергетические нагрузки здания.
        /// </summary>
        public static string BuildingForm9Name {
            get {
                return ResourceManager.GetString("BuildingForm9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здания, строения, сооружения.
        /// </summary>
        public static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обозначение и единица измерения.
        /// </summary>
        public static string DesignationAndUnit {
            get {
                return ResourceManager.GetString("DesignationAndUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетное проектное значение.
        /// </summary>
        public static string EstimatedProjectValue {
            get {
                return ResourceManager.GetString("EstimatedProjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид собственности.
        /// </summary>
        public static string FSCode {
            get {
                return ResourceManager.GetString("FSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покрытие.
        /// </summary>
        public static string IBuildingForm1Column10 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окна.
        /// </summary>
        public static string IBuildingForm1Column11 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическая (Расчетная)2.
        /// </summary>
        public static string IBuildingForm1Column12 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельная отопительная характеристика, Вт/м3оС.
        /// </summary>
        public static string IBuildingForm1Column1213 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормативная3.
        /// </summary>
        public static string IBuildingForm1Column13 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На отопление и вентиляцию.
        /// </summary>
        public static string IBuildingForm1Column14 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарный годовой расход тепловой энергии, согласно данных систем учета потребления тепловой энергии, Гкал/год.
        /// </summary>
        public static string IBuildingForm1Column1415 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column1415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На систему горячего водоснабжения.
        /// </summary>
        public static string IBuildingForm1Column15 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонение фактического  (расчетного) значения удельной отопительной характеристики от нормативной, %4.
        /// </summary>
        public static string IBuildingForm1Column16 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование / назначение здания.
        /// </summary>
        public static string IBuildingForm1Column2 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода в эксплуатацию.
        /// </summary>
        public static string IBuildingForm1Column3 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Износ %.
        /// </summary>
        public static string IBuildingForm1Column31 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отапливаемая площадь, м2.
        /// </summary>
        public static string IBuildingForm1Column4 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие характеристики.
        /// </summary>
        public static string IBuildingForm1Column4567891011 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column4567891011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Периметр, м.
        /// </summary>
        public static string IBuildingForm1Column5 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота, м.
        /// </summary>
        public static string IBuildingForm1Column6 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя температура, оС.
        /// </summary>
        public static string IBuildingForm1Column7 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стены.
        /// </summary>
        public static string IBuildingForm1Column8 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приведенное сопротивление теплопередаче, м2оС/Вт 1.
        /// </summary>
        public static string IBuildingForm1Column891011 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column891011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string IBuildingForm1Column9 {
            get {
                return ResourceManager.GetString("IBuildingForm1Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчетная информация для промышленных предприятий, имеющих здания, строения, сооружения.
        /// </summary>
        public static string IBuildingForm1Name {
            get {
                return ResourceManager.GetString("IBuildingForm1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Определяется из толщины материалов ограждающих конструкций и их теплопроводности..
        /// </summary>
        public static string IBuildingForm1SubText1 {
            get {
                return ResourceManager.GetString("IBuildingForm1SubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность отопительного периода, z__________суток;.
        /// </summary>
        public static string IBuildingForm1SubTitle1 {
            get {
                return ResourceManager.GetString("IBuildingForm1SubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя температура наружного воздуха за отопительный период базового года, tн.ср. _______оС.
        /// </summary>
        public static string IBuildingForm1SubTitle11 {
            get {
                return ResourceManager.GetString("IBuildingForm1SubTitle11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатель.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конденсатоотводчики: тип, количество.
        /// </summary>
        public static string IndustryForm10Column10 {
            get {
                return ResourceManager.GetString("IndustryForm10Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличие теплоутилизационных устройств, температура конденсата оС .
        /// </summary>
        public static string IndustryForm10Column11 {
            get {
                return ResourceManager.GetString("IndustryForm10Column11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание (характеристика загрязнений конденсата).
        /// </summary>
        public static string IndustryForm10Column12 {
            get {
                return ResourceManager.GetString("IndustryForm10Column12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение, направление использования агрегата.
        /// </summary>
        public static string IndustryForm10Column2 {
            get {
                return ResourceManager.GetString("IndustryForm10Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование агрегата, год ввода, тип, марка, вид энергоносителя.
        /// </summary>
        public static string IndustryForm10Column3 {
            get {
                return ResourceManager.GetString("IndustryForm10Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производительность агрегата (паспортная) по продукту../ч.
        /// </summary>
        public static string IndustryForm10Column4 {
            get {
                return ResourceManager.GetString("IndustryForm10Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm10Column5 {
            get {
                return ResourceManager.GetString("IndustryForm10Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление рабочее МПа.
        /// </summary>
        public static string IndustryForm10Column6 {
            get {
                return ResourceManager.GetString("IndustryForm10Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочие параметры на входе/на выходе.
        /// </summary>
        public static string IndustryForm10Column67 {
            get {
                return ResourceManager.GetString("IndustryForm10Column67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура рабочая оС.
        /// </summary>
        public static string IndustryForm10Column7 {
            get {
                return ResourceManager.GetString("IndustryForm10Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход теплоэнергии на единицу продукции Гкал/….
        /// </summary>
        public static string IndustryForm10Column8 {
            get {
                return ResourceManager.GetString("IndustryForm10Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПД по паспорту %.
        /// </summary>
        public static string IndustryForm10Column9 {
            get {
                return ResourceManager.GetString("IndustryForm10Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика технологического оборудования, использующего тепловую энергию (пар, горячая вода).
        /// </summary>
        public static string IndustryForm10Name {
            get {
                return ResourceManager.GetString("IndustryForm10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование объекта (цех, участок и др.), теплоноситель (пар, горячая вода).
        /// </summary>
        public static string IndustryForm11Column2 {
            get {
                return ResourceManager.GetString("IndustryForm11Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технологическое оборудование.
        /// </summary>
        public static string IndustryForm11Column3 {
            get {
                return ResourceManager.GetString("IndustryForm11Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отопление.
        /// </summary>
        public static string IndustryForm11Column4 {
            get {
                return ResourceManager.GetString("IndustryForm11Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При фактических значениях среднегодовой температуры, оС, и продолжительности отопительного периода, сут..
        /// </summary>
        public static string IndustryForm11Column456 {
            get {
                return ResourceManager.GetString("IndustryForm11Column456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приточная вентиляция.
        /// </summary>
        public static string IndustryForm11Column5 {
            get {
                return ResourceManager.GetString("IndustryForm11Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горячее водоснабжение.
        /// </summary>
        public static string IndustryForm11Column6 {
            get {
                return ResourceManager.GetString("IndustryForm11Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетно-нормативное потребление тепловой энергии в {0} г..
        /// </summary>
        public static string IndustryForm11Name {
            get {
                return ResourceManager.GetString("IndustryForm11Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи прихода/расхода.
        /// </summary>
        public static string IndustryForm12Column2 {
            get {
                return ResourceManager.GetString("IndustryForm12Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теплоноситель.
        /// </summary>
        public static string IndustryForm12Column3 {
            get {
                return ResourceManager.GetString("IndustryForm12Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристики, параметры.
        /// </summary>
        public static string IndustryForm12Column345 {
            get {
                return ResourceManager.GetString("IndustryForm12Column345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление Р Мпа.
        /// </summary>
        public static string IndustryForm12Column4 {
            get {
                return ResourceManager.GetString("IndustryForm12Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура оС*.
        /// </summary>
        public static string IndustryForm12Column5 {
            get {
                return ResourceManager.GetString("IndustryForm12Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарное Потребление.
        /// </summary>
        public static string IndustryForm12Column6 {
            get {
                return ResourceManager.GetString("IndustryForm12Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетно-нормативное потребление с учетом нормативных потерь.
        /// </summary>
        public static string IndustryForm12Column7 {
            get {
                return ResourceManager.GetString("IndustryForm12Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потери: эксплуатационно неизбежные/ факт..
        /// </summary>
        public static string IndustryForm12Column8 {
            get {
                return ResourceManager.GetString("IndustryForm12Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат конденсата.
        /// </summary>
        public static string IndustryForm12Column9 {
            get {
                return ResourceManager.GetString("IndustryForm12Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс потребления тепловой энергии в {0} г..
        /// </summary>
        public static string IndustryForm12Name {
            get {
                return ResourceManager.GetString("IndustryForm12Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * При теплоносителе «горячая вода» указывают температуру прямой и обратной воды..
        /// </summary>
        public static string IndustryForm12SubText1 {
            get {
                return ResourceManager.GetString("IndustryForm12SubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гкал (графы 8, 10 — в процентах).
        /// </summary>
        public static string IndustryForm12Subtitle1 {
            get {
                return ResourceManager.GetString("IndustryForm12Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение, направление использования.
        /// </summary>
        public static string IndustryForm13Column2 {
            get {
                return ResourceManager.GetString("IndustryForm13Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование агрегата, тип, марка, характерный размер, год ввода в эксплуатацию.
        /// </summary>
        public static string IndustryForm13Column3 {
            get {
                return ResourceManager.GetString("IndustryForm13Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm13Column4 {
            get {
                return ResourceManager.GetString("IndustryForm13Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производительность агрегата (паспортная) по продукту…/ч.
        /// </summary>
        public static string IndustryForm13Column5 {
            get {
                return ResourceManager.GetString("IndustryForm13Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фактически за {0} г..
        /// </summary>
        public static string IndustryForm13Column6 {
            get {
                return ResourceManager.GetString("IndustryForm13Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход топлива на единицу продукции кг. у.т./….
        /// </summary>
        public static string IndustryForm13Column67 {
            get {
                return ResourceManager.GetString("IndustryForm13Column67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норматив расхода.
        /// </summary>
        public static string IndustryForm13Column7 {
            get {
                return ResourceManager.GetString("IndustryForm13Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование и краткая характеристика теплоутилизационного оборудования, температура отходящих газов оС.
        /// </summary>
        public static string IndustryForm13Column8 {
            get {
                return ResourceManager.GetString("IndustryForm13Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика топливоиспользующих агрегатов (заполняется при наличии).
        /// </summary>
        public static string IndustryForm13Name {
            get {
                return ResourceManager.GetString("IndustryForm13Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи прихода/расхода.
        /// </summary>
        public static string IndustryForm14Column2 {
            get {
                return ResourceManager.GetString("IndustryForm14Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарное потребление энергии.
        /// </summary>
        public static string IndustryForm14Column3 {
            get {
                return ResourceManager.GetString("IndustryForm14Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расчетно-нормативное потребление с учетом нормативных потерь.
        /// </summary>
        public static string IndustryForm14Column4 {
            get {
                return ResourceManager.GetString("IndustryForm14Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В том числе.
        /// </summary>
        public static string IndustryForm14Column45 {
            get {
                return ResourceManager.GetString("IndustryForm14Column45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to потери энергии: эксплуатационно-неизбежные/факт..
        /// </summary>
        public static string IndustryForm14Column5 {
            get {
                return ResourceManager.GetString("IndustryForm14Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент полезного использования.
        /// </summary>
        public static string IndustryForm14Column6 {
            get {
                return ResourceManager.GetString("IndustryForm14Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс потребления котельно-печного топлива в {0} г. (заполняется при наличии).
        /// </summary>
        public static string IndustryForm14Name {
            get {
                return ResourceManager.GetString("IndustryForm14Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Потребление в т.у.т.).
        /// </summary>
        public static string IndustryForm14SubTitile1 {
            get {
                return ResourceManager.GetString("IndustryForm14SubTitile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ измерения расхода топлива.
        /// </summary>
        public static string IndustryForm15Column10 {
            get {
                return ResourceManager.GetString("IndustryForm15Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход топлива л/(т·км).
        /// </summary>
        public static string IndustryForm15Column11 {
            get {
                return ResourceManager.GetString("IndustryForm15Column11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество полученного топлива.
        /// </summary>
        public static string IndustryForm15Column12 {
            get {
                return ResourceManager.GetString("IndustryForm15Column12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потери топлива.
        /// </summary>
        public static string IndustryForm15Column13 {
            get {
                return ResourceManager.GetString("IndustryForm15Column13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование, (марка), тип транспортного средства, год выпуска.
        /// </summary>
        public static string IndustryForm15Column2 {
            get {
                return ResourceManager.GetString("IndustryForm15Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество транспортных средств.
        /// </summary>
        public static string IndustryForm15Column3 {
            get {
                return ResourceManager.GetString("IndustryForm15Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грузоподъемность, т, пассажировместимость чел..
        /// </summary>
        public static string IndustryForm15Column4 {
            get {
                return ResourceManager.GetString("IndustryForm15Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид использованного топлива.
        /// </summary>
        public static string IndustryForm15Column5 {
            get {
                return ResourceManager.GetString("IndustryForm15Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход топлива по паспортным данным л/км; л/(т·км).
        /// </summary>
        public static string IndustryForm15Column6 {
            get {
                return ResourceManager.GetString("IndustryForm15Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег км.
        /// </summary>
        public static string IndustryForm15Column7 {
            get {
                return ResourceManager.GetString("IndustryForm15Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовые показатели текущего года.
        /// </summary>
        public static string IndustryForm15Column78 {
            get {
                return ResourceManager.GetString("IndustryForm15Column78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем грузоперевозок т. км.
        /// </summary>
        public static string IndustryForm15Column8 {
            get {
                return ResourceManager.GetString("IndustryForm15Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество из расходованного топлива л..
        /// </summary>
        public static string IndustryForm15Column9 {
            get {
                return ResourceManager.GetString("IndustryForm15Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика использования моторных топлив транспортными средствами (заполняется при наличии).
        /// </summary>
        public static string IndustryForm15Name {
            get {
                return ResourceManager.GetString("IndustryForm15Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи прихода/расхода.
        /// </summary>
        public static string IndustryForm16Column2 {
            get {
                return ResourceManager.GetString("IndustryForm16Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарное потребление л..
        /// </summary>
        public static string IndustryForm16Column3 {
            get {
                return ResourceManager.GetString("IndustryForm16Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетно-нормативное потребление л.
        /// </summary>
        public static string IndustryForm16Column4 {
            get {
                return ResourceManager.GetString("IndustryForm16Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизбежные.
        /// </summary>
        public static string IndustryForm16Column5 {
            get {
                return ResourceManager.GetString("IndustryForm16Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потери, л..
        /// </summary>
        public static string IndustryForm16Column56 {
            get {
                return ResourceManager.GetString("IndustryForm16Column56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактические.
        /// </summary>
        public static string IndustryForm16Column6 {
            get {
                return ResourceManager.GetString("IndustryForm16Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактический удельный расход л/(т·км).
        /// </summary>
        public static string IndustryForm16Column7 {
            get {
                return ResourceManager.GetString("IndustryForm16Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс потребления моторных топлив (заполняется при наличии).
        /// </summary>
        public static string IndustryForm16Name {
            get {
                return ResourceManager.GetString("IndustryForm16Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование характеристики.
        /// </summary>
        public static string IndustryForm17Column2 {
            get {
                return ResourceManager.GetString("IndustryForm17Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение характеристики.
        /// </summary>
        public static string IndustryForm17Column4 {
            get {
                return ResourceManager.GetString("IndustryForm17Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения об использовании вторичных энергоресурсов (ВЭР), альтернативных (местных)топлив и возобновляемых источников энергии (заполняется при наличии).
        /// </summary>
        public static string IndustryForm17Name {
            get {
                return ResourceManager.GetString("IndustryForm17Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виды энергоносителей и наименование продукции (работ).
        /// </summary>
        public static string IndustryForm18Column2 {
            get {
                return ResourceManager.GetString("IndustryForm18Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовый год: фактический удельный расход общезаводской/ цеховой.
        /// </summary>
        public static string IndustryForm18Column4 {
            get {
                return ResourceManager.GetString("IndustryForm18Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to текущий год.
        /// </summary>
        public static string IndustryForm18Column5 {
            get {
                return ResourceManager.GetString("IndustryForm18Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетные удельные расходы энергоносителей (нормативы) по видам продукции с учетом реализации программы энергосбережения при объеме производства в {0} г. Обследования.
        /// </summary>
        public static string IndustryForm18Column56789 {
            get {
                return ResourceManager.GetString("IndustryForm18Column56789", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход ТЭР на выпускаемую продукцию.
        /// </summary>
        public static string IndustryForm18Name {
            get {
                return ResourceManager.GetString("IndustryForm18Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование мероприятий, вид энергоресурса.
        /// </summary>
        public static string IndustryForm19Column2 {
            get {
                return ResourceManager.GetString("IndustryForm19Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затраты тыс. тг..
        /// </summary>
        public static string IndustryForm19Column3 {
            get {
                return ResourceManager.GetString("IndustryForm19Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в натуральном выражении.
        /// </summary>
        public static string IndustryForm19Column4 {
            get {
                return ResourceManager.GetString("IndustryForm19Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовая экономия топливно-энергетических ресурсов.
        /// </summary>
        public static string IndustryForm19Column45 {
            get {
                return ResourceManager.GetString("IndustryForm19Column45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в стоимостном выражении тыс. тг. (по тарифу).
        /// </summary>
        public static string IndustryForm19Column5 {
            get {
                return ResourceManager.GetString("IndustryForm19Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласованный срок внедрения квартал, год.
        /// </summary>
        public static string IndustryForm19Column6 {
            get {
                return ResourceManager.GetString("IndustryForm19Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок окупаемости.
        /// </summary>
        public static string IndustryForm19Column7 {
            get {
                return ResourceManager.GetString("IndustryForm19Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень энергосберегающих мероприятий.
        /// </summary>
        public static string IndustryForm19Name {
            get {
                return ResourceManager.GetString("IndustryForm19Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string IndustryForm1Column2 {
            get {
                return ResourceManager.GetString("IndustryForm1Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовый год*.
        /// </summary>
        public static string IndustryForm1Column4 {
            get {
                return ResourceManager.GetString("IndustryForm1Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий год*.
        /// </summary>
        public static string IndustryForm1Column5 {
            get {
                return ResourceManager.GetString("IndustryForm1Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Отын-энергетикалық ресурс (ОЭР) құны берілген есеп шоттар бойынша айқындалады. &lt;br /&gt;
        /// 2) Мынадай формула бойынша айқындалады 3-т. мәні / 1-т. Мәні &lt;br /&gt;
        /// 3) Мынадай формула бойынша айқындалады 1-т мәні/ 3-т. мәні &lt;br /&gt;
        /// *Ағымдағы жыл – «Энергия аудиті жөніндегі шартты» жасаған жылдың күнтізбелік жылы; &lt;br /&gt;
        /// *Базалық жыл – ағымдағы жылдың алдындағы күнтізбелік жыл. &lt;br /&gt;.
        /// </summary>
        public static string industryForm1FootText {
            get {
                return ResourceManager.GetString("industryForm1FootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие сведения.
        /// </summary>
        public static string IndustryForm1Name {
            get {
                return ResourceManager.GetString("IndustryForm1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование энергоносителя.
        /// </summary>
        public static string IndustryForm2Column2 {
            get {
                return ResourceManager.GetString("IndustryForm2Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребленное количество в год.
        /// </summary>
        public static string IndustryForm2Column4 {
            get {
                return ResourceManager.GetString("IndustryForm2Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип прибора (марка).
        /// </summary>
        public static string IndustryForm2Column5 {
            get {
                return ResourceManager.GetString("IndustryForm2Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммерческий учет.
        /// </summary>
        public static string IndustryForm2Column56 {
            get {
                return ResourceManager.GetString("IndustryForm2Column56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm2Column6 {
            get {
                return ResourceManager.GetString("IndustryForm2Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее потребление энергоносителей.
        /// </summary>
        public static string IndustryForm2Name {
            get {
                return ResourceManager.GetString("IndustryForm2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производство, цех, номер подстанции.
        /// </summary>
        public static string IndustryForm3Column2 {
            get {
                return ResourceManager.GetString("IndustryForm3Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода в эксплуатацию.
        /// </summary>
        public static string IndustryForm3Column3 {
            get {
                return ResourceManager.GetString("IndustryForm3Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип трансформатора.
        /// </summary>
        public static string IndustryForm3Column4 {
            get {
                return ResourceManager.GetString("IndustryForm3Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество трансформаторов.
        /// </summary>
        public static string IndustryForm3Column5 {
            get {
                return ResourceManager.GetString("IndustryForm3Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарная мощность подстанции кВА.
        /// </summary>
        public static string IndustryForm3Column6 {
            get {
                return ResourceManager.GetString("IndustryForm3Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение кВ высшее/ низшее.
        /// </summary>
        public static string IndustryForm3Column7 {
            get {
                return ResourceManager.GetString("IndustryForm3Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о трансформаторных подстанциях (заполняется при наличии).
        /// </summary>
        public static string IndustryForm3Name {
            get {
                return ResourceManager.GetString("IndustryForm3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление использования электроэнергии.
        /// </summary>
        public static string IndustryForm4Column2 {
            get {
                return ResourceManager.GetString("IndustryForm4Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm4Column3 {
            get {
                return ResourceManager.GetString("IndustryForm4Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество и суммарная мощность, кВт, электродвигателей (в цехах, участках, производствах и т. п.).
        /// </summary>
        public static string IndustryForm4Column34 {
            get {
                return ResourceManager.GetString("IndustryForm4Column34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность.
        /// </summary>
        public static string IndustryForm4Column4 {
            get {
                return ResourceManager.GetString("IndustryForm4Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленная мощность потребителей электроэнергии по направлениям использования.
        /// </summary>
        public static string IndustryForm4Name {
            get {
                return ResourceManager.GetString("IndustryForm4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход электроэнергии факт/ норм.* кВт·ч/ 1000 м3.
        /// </summary>
        public static string IndustryForm5Column10 {
            get {
                return ResourceManager.GetString("IndustryForm5Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система охлаждения (оборотное, водопроводное и т.п).
        /// </summary>
        public static string IndustryForm5Column11 {
            get {
                return ResourceManager.GetString("IndustryForm5Column11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цех, участок, производство, тип компрессора.
        /// </summary>
        public static string IndustryForm5Column2 {
            get {
                return ResourceManager.GetString("IndustryForm5Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода в эксплуатацию.
        /// </summary>
        public static string IndustryForm5Column3 {
            get {
                return ResourceManager.GetString("IndustryForm5Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm5Column4 {
            get {
                return ResourceManager.GetString("IndustryForm5Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производительность м3/мин.
        /// </summary>
        public static string IndustryForm5Column5 {
            get {
                return ResourceManager.GetString("IndustryForm5Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление Мпа.
        /// </summary>
        public static string IndustryForm5Column6 {
            get {
                return ResourceManager.GetString("IndustryForm5Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность электропривода кВт.
        /// </summary>
        public static string IndustryForm5Column7 {
            get {
                return ResourceManager.GetString("IndustryForm5Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы компрессора за год по журналу ч, год.
        /// </summary>
        public static string IndustryForm5Column8 {
            get {
                return ResourceManager.GetString("IndustryForm5Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетный среднегодовой расход электроэнергии МВт·ч.
        /// </summary>
        public static string IndustryForm5Column9 {
            get {
                return ResourceManager.GetString("IndustryForm5Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о компрессорном оборудовании заполняется при наличии).
        /// </summary>
        public static string IndustryForm5Name {
            get {
                return ResourceManager.GetString("IndustryForm5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * В случае отсутствия нормативных (паспортных) данных рассчитывают по формуле:.
        /// </summary>
        public static string IndustryForm5SubText1 {
            get {
                return ResourceManager.GetString("IndustryForm5SubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение графы 7х1000     (Е.1) &lt;br/&gt;
        ///Значение графы        5х60.
        /// </summary>
        public static string IndustryForm5SubText2 {
            get {
                return ResourceManager.GetString("IndustryForm5SubText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип агрегата источника.
        /// </summary>
        public static string IndustryForm6Column1 {
            get {
                return ResourceManager.GetString("IndustryForm6Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода в эксплуатацию.
        /// </summary>
        public static string IndustryForm6Column2 {
            get {
                return ResourceManager.GetString("IndustryForm6Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность по холоду Гкал/ч.
        /// </summary>
        public static string IndustryForm6Column3 {
            get {
                return ResourceManager.GetString("IndustryForm6Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура в холодильной камере оС.
        /// </summary>
        public static string IndustryForm6Column4 {
            get {
                return ResourceManager.GetString("IndustryForm6Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленная мощность кВт.
        /// </summary>
        public static string IndustryForm6Column5 {
            get {
                return ResourceManager.GetString("IndustryForm6Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход электроэнергии, факт./норм. кВт·ч/Гкал.
        /// </summary>
        public static string IndustryForm6Column6 {
            get {
                return ResourceManager.GetString("IndustryForm6Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы, летом/ зимой ч/сут.
        /// </summary>
        public static string IndustryForm6Column7 {
            get {
                return ResourceManager.GetString("IndustryForm6Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход теплоносителя летом/ зимой т/ч.
        /// </summary>
        public static string IndustryForm6Column8 {
            get {
                return ResourceManager.GetString("IndustryForm6Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система отвода тепла от конденсатора.
        /// </summary>
        public static string IndustryForm6Column89 {
            get {
                return ResourceManager.GetString("IndustryForm6Column89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Охлаждение летом/зимой от до … оС.
        /// </summary>
        public static string IndustryForm6Column9 {
            get {
                return ResourceManager.GetString("IndustryForm6Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика холодильного оборудования (заполняется при наличии).
        /// </summary>
        public static string IndustryForm6Name {
            get {
                return ResourceManager.GetString("IndustryForm6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход топлива на производство электро энергии г. у.т./(кВт·ч).
        /// </summary>
        public static string IndustryForm7Column10 {
            get {
                return ResourceManager.GetString("IndustryForm7Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода ТЭС в эксплуатацию.
        /// </summary>
        public static string IndustryForm7Column2 {
            get {
                return ResourceManager.GetString("IndustryForm7Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электрическая мощность ТЭС, проектн./факт. кВт.
        /// </summary>
        public static string IndustryForm7Column3 {
            get {
                return ResourceManager.GetString("IndustryForm7Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловая мощность ТЭС, проектн./факт. Гкал.
        /// </summary>
        public static string IndustryForm7Column4 {
            get {
                return ResourceManager.GetString("IndustryForm7Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип турбоагрегата.
        /// </summary>
        public static string IndustryForm7Column5 {
            get {
                return ResourceManager.GetString("IndustryForm7Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество турбоагрегатов.
        /// </summary>
        public static string IndustryForm7Column6 {
            get {
                return ResourceManager.GetString("IndustryForm7Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент полезного действия (КПД) турбоагрегата %.
        /// </summary>
        public static string IndustryForm7Column7 {
            get {
                return ResourceManager.GetString("IndustryForm7Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовое использование турбоагрегата, проектн./факт. ч..
        /// </summary>
        public static string IndustryForm7Column8 {
            get {
                return ResourceManager.GetString("IndustryForm7Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент эффектив ности использования установленной мощности, Р факт Р уст.
        /// </summary>
        public static string IndustryForm7Column9 {
            get {
                return ResourceManager.GetString("IndustryForm7Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о составе и работе основного оборудования теплоэлектростанции (ТЭС) (заполняется при наличии).
        /// </summary>
        public static string IndustryForm7Name {
            get {
                return ResourceManager.GetString("IndustryForm7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи прихода/расхода.
        /// </summary>
        public static string IndustryForm8Column2 {
            get {
                return ResourceManager.GetString("IndustryForm8Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарное потребление.
        /// </summary>
        public static string IndustryForm8Column3 {
            get {
                return ResourceManager.GetString("IndustryForm8Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В том числе расчетно-нормативное потребление с учетом нормативных потерь.
        /// </summary>
        public static string IndustryForm8Column4 {
            get {
                return ResourceManager.GetString("IndustryForm8Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс потребления электроэнергии в {0} г./ Баланс электрической энергии в базовом году.
        /// </summary>
        public static string IndustryForm8Name {
            get {
                return ResourceManager.GetString("IndustryForm8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * При наличии внутризаводского учета электроэнергии в статье «Расход» заполняется и графа 2.
        /// </summary>
        public static string IndustryForm8SubText1 {
            get {
                return ResourceManager.GetString("IndustryForm8SubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МВтхч (графа 5 — в процентах)..
        /// </summary>
        public static string IndustryForm8Subtitle2 {
            get {
                return ResourceManager.GetString("IndustryForm8Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовой расход топлива по коммерческому учету тыс. т.у.т..
        /// </summary>
        public static string IndustryForm9Column10 {
            get {
                return ResourceManager.GetString("IndustryForm9Column10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовая выработка тепла по приборному учету Гкал.
        /// </summary>
        public static string IndustryForm9Column11 {
            get {
                return ResourceManager.GetString("IndustryForm9Column11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип котло агрегата.
        /// </summary>
        public static string IndustryForm9Column2 {
            get {
                return ResourceManager.GetString("IndustryForm9Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год ввода в эксплуатацию.
        /// </summary>
        public static string IndustryForm9Column3 {
            get {
                return ResourceManager.GetString("IndustryForm9Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string IndustryForm9Column4 {
            get {
                return ResourceManager.GetString("IndustryForm9Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производительность, проектн./факт. т/ч, Гкал/ч.
        /// </summary>
        public static string IndustryForm9Column5 {
            get {
                return ResourceManager.GetString("IndustryForm9Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление, раб./факт. Мпа.
        /// </summary>
        public static string IndustryForm9Column6 {
            get {
                return ResourceManager.GetString("IndustryForm9Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПД «брутто» по данным последних испытаний %.
        /// </summary>
        public static string IndustryForm9Column7 {
            get {
                return ResourceManager.GetString("IndustryForm9Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПД по паспорту %.
        /// </summary>
        public static string IndustryForm9Column8 {
            get {
                return ResourceManager.GetString("IndustryForm9Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удельный расход топлива на выработку тепла факт./ норм. кг у.т./ Гкал.
        /// </summary>
        public static string IndustryForm9Column9 {
            get {
                return ResourceManager.GetString("IndustryForm9Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о составе и работе котельной (заполняется при наличии).
        /// </summary>
        public static string IndustryForm9Name {
            get {
                return ResourceManager.GetString("IndustryForm9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топливо: основное — природный газ.
        /// </summary>
        public static string IndustryForm9Subtitle1 {
            get {
                return ResourceManager.GetString("IndustryForm9Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резервное .
        /// </summary>
        public static string IndustryForm9Subtitle2 {
            get {
                return ResourceManager.GetString("IndustryForm9Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормативное значение.
        /// </summary>
        public static string NormativeValue {
            get {
                return ResourceManager.GetString("NormativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормируемое значение.
        /// </summary>
        public static string RatedValue {
            get {
                return ResourceManager.GetString("RatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единица измерения.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
