//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTOR_Cmdevice
    {
        public COLLECTOR_Cmdevice()
        {
            this.COLLECTOR_IndicatorValues = new HashSet<COLLECTOR_IndicatorValues>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public Nullable<long> refIndicatorType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
        public Nullable<long> refUnit { get; set; }
        public string Address { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
    
        public virtual DIC_Unit DIC_Unit { get; set; }
        public virtual COLLECTOR_DIC_CmdeviceTypes COLLECTOR_DIC_CmdeviceTypes { get; set; }
        public virtual ICollection<COLLECTOR_IndicatorValues> COLLECTOR_IndicatorValues { get; set; }
    }
}
