//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTOR_IndicatorValues
    {
        public long Id { get; set; }
        public Nullable<double> Value { get; set; }
        public long refCmdevice { get; set; }
        public System.DateTime DatetimeStamp { get; set; }
        public Nullable<System.DateTime> ReceiveDatetime { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual COLLECTOR_Cmdevice COLLECTOR_Cmdevice { get; set; }
    }
}
