//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_GU
    {
        public DIC_GU()
        {
            this.SUB_Form3aGuRecord1 = new HashSet<SUB_Form3aGuRecord1>();
            this.SUB_Form3aGuRecord2 = new HashSet<SUB_Form3aGuRecord2>();
            this.SUB_Form3aGuRecord3 = new HashSet<SUB_Form3aGuRecord3>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<SUB_Form3aGuRecord1> SUB_Form3aGuRecord1 { get; set; }
        public virtual ICollection<SUB_Form3aGuRecord2> SUB_Form3aGuRecord2 { get; set; }
        public virtual ICollection<SUB_Form3aGuRecord3> SUB_Form3aGuRecord3 { get; set; }
    }
}
