//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Kato
    {
        public DIC_Kato()
        {
            this.DIC_Organization = new HashSet<DIC_Organization>();
            this.DIC_Organization1 = new HashSet<DIC_Organization>();
            this.DIC_Organization2 = new HashSet<DIC_Organization>();
            this.DIC_Organization3 = new HashSet<DIC_Organization>();
            this.RST_Application = new HashSet<RST_Application>();
            this.rst_obl_control = new HashSet<rst_obl_control>();
            this.RST_ReportReestr = new HashSet<RST_ReportReestr>();
            this.RST_ReportReestr1 = new HashSet<RST_ReportReestr>();
            this.RST_ReportReestr2 = new HashSet<RST_ReportReestr>();
            this.RST_ReportReestr3 = new HashSet<RST_ReportReestr>();
            this.RST_ReportReestr4 = new HashSet<RST_ReportReestr>();
            this.SEC_User = new HashSet<SEC_User>();
            this.SEC_User1 = new HashSet<SEC_User>();
            this.SEC_User2 = new HashSet<SEC_User>();
            this.SEC_User3 = new HashSet<SEC_User>();
            this.RST_ReestrReportHistory = new HashSet<RST_ReestrReportHistory>();
        }
    
        public long Id { get; set; }
        public Nullable<int> refParent { get; set; }
        public Nullable<int> type { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    
        public virtual ICollection<DIC_Organization> DIC_Organization { get; set; }
        public virtual ICollection<DIC_Organization> DIC_Organization1 { get; set; }
        public virtual ICollection<DIC_Organization> DIC_Organization2 { get; set; }
        public virtual ICollection<DIC_Organization> DIC_Organization3 { get; set; }
        public virtual ICollection<RST_Application> RST_Application { get; set; }
        public virtual ICollection<rst_obl_control> rst_obl_control { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr1 { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr2 { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr3 { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr4 { get; set; }
        public virtual ICollection<SEC_User> SEC_User { get; set; }
        public virtual ICollection<SEC_User> SEC_User1 { get; set; }
        public virtual ICollection<SEC_User> SEC_User2 { get; set; }
        public virtual ICollection<SEC_User> SEC_User3 { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
    }
}
