//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Organization
    {
        public DIC_Organization()
        {
            this.SEC_User = new HashSet<SEC_User>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string ShortNameRu { get; set; }
        public string ShortNameKz { get; set; }
        public long Oblast { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<long> SubRegion { get; set; }
        public Nullable<long> Village { get; set; }
        public string Address { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual DIC_Kato DIC_Kato { get; set; }
        public virtual DIC_Kato DIC_Kato1 { get; set; }
        public virtual DIC_Kato DIC_Kato2 { get; set; }
        public virtual DIC_Kato DIC_Kato3 { get; set; }
        public virtual ICollection<SEC_User> SEC_User { get; set; }
    }
}
