//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Unit
    {
        public DIC_Unit()
        {
            this.COLLECTOR_Cmdevice = new HashSet<COLLECTOR_Cmdevice>();
            this.EAUDIT_DIC_TypeResource = new HashSet<EAUDIT_DIC_TypeResource>();
            this.EAUDIT_DIC_TypeResource1 = new HashSet<EAUDIT_DIC_TypeResource>();
            this.EAUDIT_IndustryForm1 = new HashSet<EAUDIT_IndustryForm1>();
            this.SUB_DIC_KindResource = new HashSet<SUB_DIC_KindResource>();
            this.SUB_DIC_TypeResource = new HashSet<SUB_DIC_TypeResource>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<COLLECTOR_Cmdevice> COLLECTOR_Cmdevice { get; set; }
        public virtual ICollection<EAUDIT_DIC_TypeResource> EAUDIT_DIC_TypeResource { get; set; }
        public virtual ICollection<EAUDIT_DIC_TypeResource> EAUDIT_DIC_TypeResource1 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm1> EAUDIT_IndustryForm1 { get; set; }
        public virtual ICollection<SUB_DIC_KindResource> SUB_DIC_KindResource { get; set; }
        public virtual ICollection<SUB_DIC_TypeResource> SUB_DIC_TypeResource { get; set; }
    }
}
