//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_OwnedFacility
    {
        public EAUDIT_OwnedFacility()
        {
            this.EAUDIT_IndustryForm1 = new HashSet<EAUDIT_IndustryForm1>();
            this.EAUDIT_IndustryForm10 = new HashSet<EAUDIT_IndustryForm10>();
            this.EAUDIT_IndustryForm11 = new HashSet<EAUDIT_IndustryForm11>();
            this.EAUDIT_IndustryForm12 = new HashSet<EAUDIT_IndustryForm12>();
            this.EAUDIT_IndustryForm13 = new HashSet<EAUDIT_IndustryForm13>();
            this.EAUDIT_IndustryForm14 = new HashSet<EAUDIT_IndustryForm14>();
            this.EAUDIT_IndustryForm15 = new HashSet<EAUDIT_IndustryForm15>();
            this.EAUDIT_IndustryForm16 = new HashSet<EAUDIT_IndustryForm16>();
            this.EAUDIT_IndustryForm17 = new HashSet<EAUDIT_IndustryForm17>();
            this.EAUDIT_IndustryForm18 = new HashSet<EAUDIT_IndustryForm18>();
            this.EAUDIT_IndustryForm19 = new HashSet<EAUDIT_IndustryForm19>();
            this.EAUDIT_IndustryForm2 = new HashSet<EAUDIT_IndustryForm2>();
            this.EAUDIT_IndustryForm3 = new HashSet<EAUDIT_IndustryForm3>();
            this.EAUDIT_IndustryForm4 = new HashSet<EAUDIT_IndustryForm4>();
            this.EAUDIT_IndustryForm4_Shop = new HashSet<EAUDIT_IndustryForm4_Shop>();
            this.EAUDIT_IndustryForm5 = new HashSet<EAUDIT_IndustryForm5>();
            this.EAUDIT_IndustryForm6 = new HashSet<EAUDIT_IndustryForm6>();
            this.EAUDIT_IndustryForm7 = new HashSet<EAUDIT_IndustryForm7>();
            this.EAUDIT_IndustryForm8 = new HashSet<EAUDIT_IndustryForm8>();
            this.EAUDIT_IndustryForm9 = new HashSet<EAUDIT_IndustryForm9>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long refPreamble { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual ICollection<EAUDIT_IndustryForm1> EAUDIT_IndustryForm1 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm10> EAUDIT_IndustryForm10 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm11> EAUDIT_IndustryForm11 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm12> EAUDIT_IndustryForm12 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm13> EAUDIT_IndustryForm13 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm14> EAUDIT_IndustryForm14 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm15> EAUDIT_IndustryForm15 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm16> EAUDIT_IndustryForm16 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm17> EAUDIT_IndustryForm17 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm18> EAUDIT_IndustryForm18 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm19> EAUDIT_IndustryForm19 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm2> EAUDIT_IndustryForm2 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm3> EAUDIT_IndustryForm3 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4> EAUDIT_IndustryForm4 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4_Shop> EAUDIT_IndustryForm4_Shop { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm5> EAUDIT_IndustryForm5 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm6> EAUDIT_IndustryForm6 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm7> EAUDIT_IndustryForm7 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm8> EAUDIT_IndustryForm8 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm9> EAUDIT_IndustryForm9 { get; set; }
        public virtual EAUDIT_Preamble EAUDIT_Preamble { get; set; }
    }
}
