//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_DIC_TypeResource
    {
        public EAUDIT_DIC_TypeResource()
        {
            this.EAUDIT_BuildingForm1 = new HashSet<EAUDIT_BuildingForm1>();
            this.EAUDIT_BuildingForm2 = new HashSet<EAUDIT_BuildingForm2>();
            this.EAUDIT_BuildingForm3 = new HashSet<EAUDIT_BuildingForm3>();
            this.EAUDIT_BuildingForm4 = new HashSet<EAUDIT_BuildingForm4>();
            this.EAUDIT_BuildingForm5 = new HashSet<EAUDIT_BuildingForm5>();
            this.EAUDIT_BuildingForm6 = new HashSet<EAUDIT_BuildingForm6>();
            this.EAUDIT_BuildingForm7 = new HashSet<EAUDIT_BuildingForm7>();
            this.EAUDIT_BuildingForm9 = new HashSet<EAUDIT_BuildingForm9>();
            this.EAUDIT_IndustryForm4_ShopValues = new HashSet<EAUDIT_IndustryForm4_ShopValues>();
            this.EAUDIT_IndustryForm1 = new HashSet<EAUDIT_IndustryForm1>();
            this.EAUDIT_IndustryForm11 = new HashSet<EAUDIT_IndustryForm11>();
            this.EAUDIT_IndustryForm12 = new HashSet<EAUDIT_IndustryForm12>();
            this.EAUDIT_IndustryForm14 = new HashSet<EAUDIT_IndustryForm14>();
            this.EAUDIT_IndustryForm16 = new HashSet<EAUDIT_IndustryForm16>();
            this.EAUDIT_IndustryForm17 = new HashSet<EAUDIT_IndustryForm17>();
            this.EAUDIT_IndustryForm18 = new HashSet<EAUDIT_IndustryForm18>();
            this.EAUDIT_IndustryForm19 = new HashSet<EAUDIT_IndustryForm19>();
            this.EAUDIT_IndustryForm2 = new HashSet<EAUDIT_IndustryForm2>();
            this.EAUDIT_IndustryForm4 = new HashSet<EAUDIT_IndustryForm4>();
            this.EAUDIT_IndustryForm8 = new HashSet<EAUDIT_IndustryForm8>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> PosIndex { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> refUnit { get; set; }
        public string FormCode { get; set; }
        public Nullable<long> refUnit2 { get; set; }
        public string Number { get; set; }
        public string Designation { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
    
        public virtual DIC_Unit DIC_Unit { get; set; }
        public virtual DIC_Unit DIC_Unit1 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm1> EAUDIT_BuildingForm1 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm2> EAUDIT_BuildingForm2 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm3> EAUDIT_BuildingForm3 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm4> EAUDIT_BuildingForm4 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm5> EAUDIT_BuildingForm5 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm6> EAUDIT_BuildingForm6 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm7> EAUDIT_BuildingForm7 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm9> EAUDIT_BuildingForm9 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4_ShopValues> EAUDIT_IndustryForm4_ShopValues { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm1> EAUDIT_IndustryForm1 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm11> EAUDIT_IndustryForm11 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm12> EAUDIT_IndustryForm12 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm14> EAUDIT_IndustryForm14 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm16> EAUDIT_IndustryForm16 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm17> EAUDIT_IndustryForm17 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm18> EAUDIT_IndustryForm18 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm19> EAUDIT_IndustryForm19 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm2> EAUDIT_IndustryForm2 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4> EAUDIT_IndustryForm4 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm8> EAUDIT_IndustryForm8 { get; set; }
    }
}
