//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_IndustryForm4_ShopValues
    {
        public long Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Power { get; set; }
        public long refShop { get; set; }
        public long refIndustryForm4 { get; set; }
        public long refTypeResource { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual EAUDIT_DIC_TypeResource EAUDIT_DIC_TypeResource { get; set; }
        public virtual EAUDIT_IndustryForm4 EAUDIT_IndustryForm4 { get; set; }
    }
}
