//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_Building
    {
        public EAUDIT_Building()
        {
            this.EAUDIT_BuildingForm1 = new HashSet<EAUDIT_BuildingForm1>();
            this.EAUDIT_BuildingForm2 = new HashSet<EAUDIT_BuildingForm2>();
            this.EAUDIT_BuildingForm3 = new HashSet<EAUDIT_BuildingForm3>();
            this.EAUDIT_BuildingForm4 = new HashSet<EAUDIT_BuildingForm4>();
            this.EAUDIT_BuildingForm5 = new HashSet<EAUDIT_BuildingForm5>();
            this.EAUDIT_BuildingForm6 = new HashSet<EAUDIT_BuildingForm6>();
            this.EAUDIT_BuildingForm7 = new HashSet<EAUDIT_BuildingForm7>();
            this.EAUDIT_BuildingForm9 = new HashSet<EAUDIT_BuildingForm9>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long refPreamble { get; set; }
        public string Customer { get; set; }
        public string Address { get; set; }
        public Nullable<int> YearOfConstruction { get; set; }
        public string Type { get; set; }
        public Nullable<int> NumberofFloors { get; set; }
        public Nullable<double> GeneralArea { get; set; }
        public Nullable<double> HeatingArea { get; set; }
        public string EnergyEfficiencyClass { get; set; }
        public Nullable<double> NormativeHeatConsumption { get; set; }
        public Nullable<double> ActualHeatConsumption { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual EAUDIT_Preamble EAUDIT_Preamble { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm1> EAUDIT_BuildingForm1 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm2> EAUDIT_BuildingForm2 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm3> EAUDIT_BuildingForm3 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm4> EAUDIT_BuildingForm4 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm5> EAUDIT_BuildingForm5 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm6> EAUDIT_BuildingForm6 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm7> EAUDIT_BuildingForm7 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm9> EAUDIT_BuildingForm9 { get; set; }
    }
}
