//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_IndustryBuildingForm1
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> YearExplonation { get; set; }
        public Nullable<double> Wear { get; set; }
        public Nullable<double> GeneralParamheatingArea { get; set; }
        public Nullable<double> GeneralParamPerimeter { get; set; }
        public Nullable<double> GeneralParamHeight { get; set; }
        public Nullable<double> GeneralParamInternalTemperature { get; set; }
        public Nullable<double> GeneralParamHeatTransferResistanceWall { get; set; }
        public Nullable<double> GeneralParamHeatTransferResistanceFloor { get; set; }
        public Nullable<double> GeneralParamHeatTransferResistanceCoating { get; set; }
        public Nullable<double> GeneralparamHeatTransferResistanceWindow { get; set; }
        public Nullable<double> SpecificHeatingCurveFact { get; set; }
        public Nullable<double> SpecificHeatingCurveStandart { get; set; }
        public Nullable<double> TotalAnnualConsumtionHeatingAndVentilation { get; set; }
        public Nullable<double> TotalAnnualConsumtionHotWaterSystem { get; set; }
        public Nullable<double> Deviation { get; set; }
        public long refPreamble { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual EAUDIT_Preamble EAUDIT_Preamble { get; set; }
    }
}
