//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_Preamble
    {
        public EAUDIT_Preamble()
        {
            this.EAUDIT_AttachedFiles = new HashSet<EAUDIT_AttachedFiles>();
            this.EAUDIT_Building = new HashSet<EAUDIT_Building>();
            this.EAUDIT_BuildingForm1 = new HashSet<EAUDIT_BuildingForm1>();
            this.EAUDIT_BuildingForm2 = new HashSet<EAUDIT_BuildingForm2>();
            this.EAUDIT_BuildingForm3 = new HashSet<EAUDIT_BuildingForm3>();
            this.EAUDIT_BuildingForm4 = new HashSet<EAUDIT_BuildingForm4>();
            this.EAUDIT_BuildingForm5 = new HashSet<EAUDIT_BuildingForm5>();
            this.EAUDIT_BuildingForm6 = new HashSet<EAUDIT_BuildingForm6>();
            this.EAUDIT_BuildingForm7 = new HashSet<EAUDIT_BuildingForm7>();
            this.EAUDIT_BuildingForm9 = new HashSet<EAUDIT_BuildingForm9>();
            this.EAUDIT_FormHistory = new HashSet<EAUDIT_FormHistory>();
            this.EAUDIT_IndustryBuildingForm1 = new HashSet<EAUDIT_IndustryBuildingForm1>();
            this.EAUDIT_IndustryForm1 = new HashSet<EAUDIT_IndustryForm1>();
            this.EAUDIT_IndustryForm10 = new HashSet<EAUDIT_IndustryForm10>();
            this.EAUDIT_IndustryForm11 = new HashSet<EAUDIT_IndustryForm11>();
            this.EAUDIT_IndustryForm12 = new HashSet<EAUDIT_IndustryForm12>();
            this.EAUDIT_IndustryForm13 = new HashSet<EAUDIT_IndustryForm13>();
            this.EAUDIT_IndustryForm14 = new HashSet<EAUDIT_IndustryForm14>();
            this.EAUDIT_IndustryForm15 = new HashSet<EAUDIT_IndustryForm15>();
            this.EAUDIT_IndustryForm16 = new HashSet<EAUDIT_IndustryForm16>();
            this.EAUDIT_IndustryForm17 = new HashSet<EAUDIT_IndustryForm17>();
            this.EAUDIT_IndustryForm18 = new HashSet<EAUDIT_IndustryForm18>();
            this.EAUDIT_IndustryForm19 = new HashSet<EAUDIT_IndustryForm19>();
            this.EAUDIT_IndustryForm2 = new HashSet<EAUDIT_IndustryForm2>();
            this.EAUDIT_IndustryForm3 = new HashSet<EAUDIT_IndustryForm3>();
            this.EAUDIT_IndustryForm4 = new HashSet<EAUDIT_IndustryForm4>();
            this.EAUDIT_IndustryForm4_Shop = new HashSet<EAUDIT_IndustryForm4_Shop>();
            this.EAUDIT_IndustryForm5 = new HashSet<EAUDIT_IndustryForm5>();
            this.EAUDIT_IndustryForm6 = new HashSet<EAUDIT_IndustryForm6>();
            this.EAUDIT_IndustryForm7 = new HashSet<EAUDIT_IndustryForm7>();
            this.EAUDIT_IndustryForm8 = new HashSet<EAUDIT_IndustryForm8>();
            this.EAUDIT_IndustryForm9 = new HashSet<EAUDIT_IndustryForm9>();
            this.EAUDIT_OwnedFacility = new HashSet<EAUDIT_OwnedFacility>();
        }
    
        public long Id { get; set; }
        public long refEauditObject { get; set; }
        public Nullable<long> refAuditor { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ReportYear { get; set; }
        public string EauditObjectsFormOfIncorporation { get; set; }
        public string EauditObjectAddress { get; set; }
        public string EauditObjectBankrequisites { get; set; }
        public string EauditObjectHead { get; set; }
        public string AuditorFormOfIncorporation { get; set; }
        public string AuditorAddress { get; set; }
        public string AuditorBankrequisites { get; set; }
        public string AuditorHead { get; set; }
        public Nullable<int> BaseYear { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string AuditorName { get; set; }
        public string EauditObjectName { get; set; }
        public Nullable<long> refDicStatus { get; set; }
        public Nullable<long> refInspector { get; set; }
        public Nullable<bool> IsSigned { get; set; }
        public Nullable<long> temp_id { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
    
        public virtual ICollection<EAUDIT_AttachedFiles> EAUDIT_AttachedFiles { get; set; }
        public virtual ICollection<EAUDIT_Building> EAUDIT_Building { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm1> EAUDIT_BuildingForm1 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm2> EAUDIT_BuildingForm2 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm3> EAUDIT_BuildingForm3 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm4> EAUDIT_BuildingForm4 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm5> EAUDIT_BuildingForm5 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm6> EAUDIT_BuildingForm6 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm7> EAUDIT_BuildingForm7 { get; set; }
        public virtual ICollection<EAUDIT_BuildingForm9> EAUDIT_BuildingForm9 { get; set; }
        public virtual EAUDIT_DIC_Statuses EAUDIT_DIC_Statuses { get; set; }
        public virtual ICollection<EAUDIT_FormHistory> EAUDIT_FormHistory { get; set; }
        public virtual ICollection<EAUDIT_IndustryBuildingForm1> EAUDIT_IndustryBuildingForm1 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm1> EAUDIT_IndustryForm1 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm10> EAUDIT_IndustryForm10 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm11> EAUDIT_IndustryForm11 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm12> EAUDIT_IndustryForm12 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm13> EAUDIT_IndustryForm13 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm14> EAUDIT_IndustryForm14 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm15> EAUDIT_IndustryForm15 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm16> EAUDIT_IndustryForm16 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm17> EAUDIT_IndustryForm17 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm18> EAUDIT_IndustryForm18 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm19> EAUDIT_IndustryForm19 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm2> EAUDIT_IndustryForm2 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm3> EAUDIT_IndustryForm3 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4> EAUDIT_IndustryForm4 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm4_Shop> EAUDIT_IndustryForm4_Shop { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm5> EAUDIT_IndustryForm5 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm6> EAUDIT_IndustryForm6 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm7> EAUDIT_IndustryForm7 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm8> EAUDIT_IndustryForm8 { get; set; }
        public virtual ICollection<EAUDIT_IndustryForm9> EAUDIT_IndustryForm9 { get; set; }
        public virtual ICollection<EAUDIT_OwnedFacility> EAUDIT_OwnedFacility { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual SEC_User SEC_User2 { get; set; }
    }
}
