//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_FieldComments
    {
        public long Id { get; set; }
        public string FieldName { get; set; }
        public long RowId { get; set; }
        public string FormCode { get; set; }
        public string Comment { get; set; }
        public System.DateTime DatetimeStamp { get; set; }
        public string UserName { get; set; }
        public bool IsError { get; set; }
        public string FieldValue { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    }
}
