//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_IndustryForm10
    {
        public long Id { get; set; }
        public string EquipmentPurpose { get; set; }
        public string EquipmentNameYearType { get; set; }
        public Nullable<double> EquipmentPerfomancePassport { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> OperatingParameterPressure { get; set; }
        public Nullable<double> OperatingParameterTemperature { get; set; }
        public Nullable<double> SpecificThermalEnergyConsumption { get; set; }
        public Nullable<double> EfficiencyPassport { get; set; }
        public string Condensate { get; set; }
        public string HeatRecoveryDevice { get; set; }
        public string Note { get; set; }
        public long refPreamble { get; set; }
        public Nullable<long> refOwnedFacility { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual EAUDIT_OwnedFacility EAUDIT_OwnedFacility { get; set; }
        public virtual EAUDIT_Preamble EAUDIT_Preamble { get; set; }
    }
}
