//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_AuditorReestr
    {
        public long Id { get; set; }
        public Nullable<long> refStatus { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual EAUDIT_DIC_Statuses EAUDIT_DIC_Statuses { get; set; }
        public virtual EAUDIT_AuditorReestr EAUDIT_AuditorReestr1 { get; set; }
        public virtual EAUDIT_AuditorReestr EAUDIT_AuditorReestr2 { get; set; }
    }
}
