//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAUDIT_DIC_Statuses
    {
        public EAUDIT_DIC_Statuses()
        {
            this.EAUDIT_AuditorReestr = new HashSet<EAUDIT_AuditorReestr>();
            this.EAUDIT_Preamble = new HashSet<EAUDIT_Preamble>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> authorid { get; set; }
    
        public virtual ICollection<EAUDIT_AuditorReestr> EAUDIT_AuditorReestr { get; set; }
        public virtual ICollection<EAUDIT_Preamble> EAUDIT_Preamble { get; set; }
    }
}
