//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aisgerEntities : DbContext
    {
        public aisgerEntities()
            : base("name=aisgerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COLLECTOR_Cmdevice> COLLECTOR_Cmdevice { get; set; }
        public DbSet<COLLECTOR_DIC_CmdeviceTypes> COLLECTOR_DIC_CmdeviceTypes { get; set; }
        public DbSet<COLLECTOR_IndicatorValues> COLLECTOR_IndicatorValues { get; set; }
        public DbSet<DIC_Department> DIC_Department { get; set; }
        public DbSet<DIC_GU> DIC_GU { get; set; }
        public DbSet<DIC_Holidays> DIC_Holidays { get; set; }
        public DbSet<DIC_Kato> DIC_Kato { get; set; }
        public DbSet<DIC_KindUser> DIC_KindUser { get; set; }
        public DbSet<DIC_OKED> DIC_OKED { get; set; }
        public DbSet<DIC_Organization> DIC_Organization { get; set; }
        public DbSet<DIC_TypeApplication> DIC_TypeApplication { get; set; }
        public DbSet<DIC_Unit> DIC_Unit { get; set; }
        public DbSet<EAUDIT_AttachedFiles> EAUDIT_AttachedFiles { get; set; }
        public DbSet<EAUDIT_AuditorReestr> EAUDIT_AuditorReestr { get; set; }
        public DbSet<EAUDIT_Building> EAUDIT_Building { get; set; }
        public DbSet<EAUDIT_BuildingForm1> EAUDIT_BuildingForm1 { get; set; }
        public DbSet<EAUDIT_BuildingForm2> EAUDIT_BuildingForm2 { get; set; }
        public DbSet<EAUDIT_BuildingForm3> EAUDIT_BuildingForm3 { get; set; }
        public DbSet<EAUDIT_BuildingForm4> EAUDIT_BuildingForm4 { get; set; }
        public DbSet<EAUDIT_BuildingForm5> EAUDIT_BuildingForm5 { get; set; }
        public DbSet<EAUDIT_BuildingForm6> EAUDIT_BuildingForm6 { get; set; }
        public DbSet<EAUDIT_BuildingForm7> EAUDIT_BuildingForm7 { get; set; }
        public DbSet<EAUDIT_BuildingForm9> EAUDIT_BuildingForm9 { get; set; }
        public DbSet<EAUDIT_DIC_Statuses> EAUDIT_DIC_Statuses { get; set; }
        public DbSet<EAUDIT_DIC_TypeResource> EAUDIT_DIC_TypeResource { get; set; }
        public DbSet<EAUDIT_FieldComments> EAUDIT_FieldComments { get; set; }
        public DbSet<EAUDIT_FormHistory> EAUDIT_FormHistory { get; set; }
        public DbSet<EAUDIT_IndustryBuildingForm1> EAUDIT_IndustryBuildingForm1 { get; set; }
        public DbSet<EAUDIT_IndustryForm1> EAUDIT_IndustryForm1 { get; set; }
        public DbSet<EAUDIT_IndustryForm10> EAUDIT_IndustryForm10 { get; set; }
        public DbSet<EAUDIT_IndustryForm11> EAUDIT_IndustryForm11 { get; set; }
        public DbSet<EAUDIT_IndustryForm12> EAUDIT_IndustryForm12 { get; set; }
        public DbSet<EAUDIT_IndustryForm13> EAUDIT_IndustryForm13 { get; set; }
        public DbSet<EAUDIT_IndustryForm14> EAUDIT_IndustryForm14 { get; set; }
        public DbSet<EAUDIT_IndustryForm15> EAUDIT_IndustryForm15 { get; set; }
        public DbSet<EAUDIT_IndustryForm16> EAUDIT_IndustryForm16 { get; set; }
        public DbSet<EAUDIT_IndustryForm17> EAUDIT_IndustryForm17 { get; set; }
        public DbSet<EAUDIT_IndustryForm18> EAUDIT_IndustryForm18 { get; set; }
        public DbSet<EAUDIT_IndustryForm19> EAUDIT_IndustryForm19 { get; set; }
        public DbSet<EAUDIT_IndustryForm2> EAUDIT_IndustryForm2 { get; set; }
        public DbSet<EAUDIT_IndustryForm3> EAUDIT_IndustryForm3 { get; set; }
        public DbSet<EAUDIT_IndustryForm4> EAUDIT_IndustryForm4 { get; set; }
        public DbSet<EAUDIT_IndustryForm4_Shop> EAUDIT_IndustryForm4_Shop { get; set; }
        public DbSet<EAUDIT_IndustryForm4_ShopValues> EAUDIT_IndustryForm4_ShopValues { get; set; }
        public DbSet<EAUDIT_IndustryForm5> EAUDIT_IndustryForm5 { get; set; }
        public DbSet<EAUDIT_IndustryForm6> EAUDIT_IndustryForm6 { get; set; }
        public DbSet<EAUDIT_IndustryForm7> EAUDIT_IndustryForm7 { get; set; }
        public DbSet<EAUDIT_IndustryForm8> EAUDIT_IndustryForm8 { get; set; }
        public DbSet<EAUDIT_IndustryForm9> EAUDIT_IndustryForm9 { get; set; }
        public DbSet<EAUDIT_OwnedFacility> EAUDIT_OwnedFacility { get; set; }
        public DbSet<EAUDIT_Preamble> EAUDIT_Preamble { get; set; }
        public DbSet<ESCO_DIC_Product> ESCO_DIC_Product { get; set; }
        public DbSet<ESCO_DIC_ProductKind> ESCO_DIC_ProductKind { get; set; }
        public DbSet<ESCO_DIC_ProductKindOked> ESCO_DIC_ProductKindOked { get; set; }
        public DbSet<i_i18n> i_i18n { get; set; }
        public DbSet<MAP_Application> MAP_Application { get; set; }
        public DbSet<MAP_ApplicationEE2> MAP_ApplicationEE2 { get; set; }
        public DbSet<MAP_ApplicationEvent> MAP_ApplicationEvent { get; set; }
        public DbSet<MAP_ApplicationHistory> MAP_ApplicationHistory { get; set; }
        public DbSet<MAP_ApplicationProduct> MAP_ApplicationProduct { get; set; }
        public DbSet<MAP_DIC_EEDetailModels> MAP_DIC_EEDetailModels { get; set; }
        public DbSet<MAP_DIC_EEDetails> MAP_DIC_EEDetails { get; set; }
        public DbSet<MAP_DIC_EEStatus> MAP_DIC_EEStatus { get; set; }
        public DbSet<MAP_DIC_Status> MAP_DIC_Status { get; set; }
        public DbSet<MAP_FormEE2> MAP_FormEE2 { get; set; }
        public DbSet<Map_FormEE2Record> Map_FormEE2Record { get; set; }
        public DbSet<MAP_Project> MAP_Project { get; set; }
        public DbSet<RST_Application> RST_Application { get; set; }
        public DbSet<RST_DIC_CodeOblast> RST_DIC_CodeOblast { get; set; }
        public DbSet<RST_DIC_Reason> RST_DIC_Reason { get; set; }
        public DbSet<RST_DIC_Status> RST_DIC_Status { get; set; }
        public DbSet<RST_DIC_StatusHistory> RST_DIC_StatusHistory { get; set; }
        public DbSet<RST_Executed> RST_Executed { get; set; }
        public DbSet<rst_obl_control> rst_obl_control { get; set; }
        public DbSet<RST_Reestr> RST_Reestr { get; set; }
        public DbSet<RST_ReestrHistory> RST_ReestrHistory { get; set; }
        public DbSet<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
        public DbSet<RST_Report> RST_Report { get; set; }
        public DbSet<RST_ReportReestr> RST_ReportReestr { get; set; }
        public DbSet<rst_reportreestroked> rst_reportreestroked { get; set; }
        public DbSet<SEC_DIC_EventType> SEC_DIC_EventType { get; set; }
        public DbSet<SEC_JurEvent> SEC_JurEvent { get; set; }
        public DbSet<SEC_RightPermission> SEC_RightPermission { get; set; }
        public DbSet<SEC_RolePermission> SEC_RolePermission { get; set; }
        public DbSet<SEC_Roles> SEC_Roles { get; set; }
        public DbSet<SEC_User> SEC_User { get; set; }
        public DbSet<SEC_UserHistory> SEC_UserHistory { get; set; }
        public DbSet<SEC_UserKind> SEC_UserKind { get; set; }
        public DbSet<SEC_UserOked> SEC_UserOked { get; set; }
        public DbSet<SEC_UserToken> SEC_UserToken { get; set; }
        public DbSet<SUB_ActionComment> SUB_ActionComment { get; set; }
        public DbSet<SUB_ActionComRecord> SUB_ActionComRecord { get; set; }
        public DbSet<SUB_ActionHistory> SUB_ActionHistory { get; set; }
        public DbSet<SUB_ActionPlan> SUB_ActionPlan { get; set; }
        public DbSet<SUB_ActionRecordHistory> SUB_ActionRecordHistory { get; set; }
        public DbSet<SUB_ActionTab1> SUB_ActionTab1 { get; set; }
        public DbSet<SUB_ActionTab2> SUB_ActionTab2 { get; set; }
        public DbSet<SUB_ActionTab3> SUB_ActionTab3 { get; set; }
        public DbSet<sub_dic_energyindicator> sub_dic_energyindicator { get; set; }
        public DbSet<SUB_DIC_Event> SUB_DIC_Event { get; set; }
        public DbSet<SUB_DIC_KindResource> SUB_DIC_KindResource { get; set; }
        public DbSet<SUB_DIC_KindTabOne> SUB_DIC_KindTabOne { get; set; }
        public DbSet<SUB_DIC_KindTabTwo> SUB_DIC_KindTabTwo { get; set; }
        public DbSet<SUB_DIC_NormEnergy> SUB_DIC_NormEnergy { get; set; }
        public DbSet<SUB_DIC_Status> SUB_DIC_Status { get; set; }
        public DbSet<SUB_DIC_TypeCounter> SUB_DIC_TypeCounter { get; set; }
        public DbSet<SUB_DIC_TypeResource> SUB_DIC_TypeResource { get; set; }
        public DbSet<SUB_Form> SUB_Form { get; set; }
        public DbSet<SUB_Form2Gu> SUB_Form2Gu { get; set; }
        public DbSet<SUB_Form2Record> SUB_Form2Record { get; set; }
        public DbSet<SUB_Form3aGuRecord1> SUB_Form3aGuRecord1 { get; set; }
        public DbSet<SUB_Form3aGuRecord2> SUB_Form3aGuRecord2 { get; set; }
        public DbSet<SUB_Form3aGuRecord3> SUB_Form3aGuRecord3 { get; set; }
        public DbSet<SUB_Form3Gu> SUB_Form3Gu { get; set; }
        public DbSet<SUB_Form3GuRecord> SUB_Form3GuRecord { get; set; }
        public DbSet<SUB_Form3Record> SUB_Form3Record { get; set; }
        public DbSet<SUB_Form4Record> SUB_Form4Record { get; set; }
        public DbSet<SUB_Form5Record> SUB_Form5Record { get; set; }
        public DbSet<SUB_Form6Record> SUB_Form6Record { get; set; }
        public DbSet<SUB_FormComment> SUB_FormComment { get; set; }
        public DbSet<SUB_FormComRecord> SUB_FormComRecord { get; set; }
        public DbSet<SUB_FormGuLightingInfo> SUB_FormGuLightingInfo { get; set; }
        public DbSet<SUB_FormHistory> SUB_FormHistory { get; set; }
        public DbSet<SUB_FormKadastr> SUB_FormKadastr { get; set; }
        public DbSet<SUB_FormRecordHistory> SUB_FormRecordHistory { get; set; }
        public DbSet<SUB_FormTab1> SUB_FormTab1 { get; set; }
        public DbSet<SUB_FormTab2> SUB_FormTab2 { get; set; }
        public DbSet<SUB_FormTab3> SUB_FormTab3 { get; set; }
        public DbSet<VIEW_COLL_IndicatorValuesPerDay> VIEW_COLL_IndicatorValuesPerDay { get; set; }
    }
}
