//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCO_DIC_ProductKindOked
    {
        public long Id { get; set; }
        public Nullable<long> KindId { get; set; }
        public Nullable<long> OkedId { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual DIC_OKED DIC_OKED { get; set; }
        public virtual ESCO_DIC_ProductKind ESCO_DIC_ProductKind { get; set; }
    }
}
