//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCO_DIC_ProductKind
    {
        public ESCO_DIC_ProductKind()
        {
            this.ESCO_DIC_Product = new HashSet<ESCO_DIC_Product>();
            this.ESCO_DIC_ProductKindOked = new HashSet<ESCO_DIC_ProductKindOked>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameGroup { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public string authorlogin { get; set; }
    
        public virtual ICollection<ESCO_DIC_Product> ESCO_DIC_Product { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<ESCO_DIC_ProductKindOked> ESCO_DIC_ProductKindOked { get; set; }
    }
}
