//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ApplicationHistory
    {
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Note { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<long> ApplcationId { get; set; }
        public string authorlogin { get; set; }
    
        public virtual MAP_Application MAP_Application { get; set; }
        public virtual MAP_DIC_Status MAP_DIC_Status { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
