//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ApplicationProduct
    {
        public long Id { get; set; }
        public Nullable<long> ApplcationId { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public string ProductVolume { get; set; }
        public string Disrciminator { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual MAP_Application MAP_Application { get; set; }
    }
}
