//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ApplicationEvent
    {
        public long Id { get; set; }
        public Nullable<long> ApplcationId { get; set; }
        public string EventName { get; set; }
        public Nullable<double> PlanExpend { get; set; }
        public string SavedEnergy { get; set; }
        public string SavedCost { get; set; }
        public Nullable<float> PaybackPeriod { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual MAP_Application MAP_Application { get; set; }
    }
}
