//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_DIC_Status
    {
        public MAP_DIC_Status()
        {
            this.MAP_Application = new HashSet<MAP_Application>();
            this.MAP_ApplicationHistory = new HashSet<MAP_ApplicationHistory>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
    
        public virtual ICollection<MAP_Application> MAP_Application { get; set; }
        public virtual ICollection<MAP_ApplicationHistory> MAP_ApplicationHistory { get; set; }
    }
}
