//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_FormEE2Record
    {
        public long Id { get; set; }
        public long FormEE2Id { get; set; }
        public int ReportYear { get; set; }
        public Nullable<double> EnergySource { get; set; }
        public Nullable<double> ExpenceEnergy { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual MAP_FormEE2 MAP_FormEE2 { get; set; }
    }
}
