//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_Application
    {
        public MAP_Application()
        {
            this.MAP_ApplicationEvent = new HashSet<MAP_ApplicationEvent>();
            this.MAP_ApplicationHistory = new HashSet<MAP_ApplicationHistory>();
            this.MAP_ApplicationProduct = new HashSet<MAP_ApplicationProduct>();
            this.MAP_Project = new HashSet<MAP_Project>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> Editor { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> DesignDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string DesignNote { get; set; }
        public string ProjectName { get; set; }
        public string ProjectObjective { get; set; }
        public string ProjectLocation { get; set; }
        public string EstimatedPeriod { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public string ExpectedResult { get; set; }
        public string CurrentState { get; set; }
        public Nullable<long> StatusId { get; set; }
        public string ProjectPowerUnit { get; set; }
        public string ProjectPowerVolume { get; set; }
        public Nullable<double> TermCost { get; set; }
        public Nullable<double> OwnFonds { get; set; }
        public Nullable<double> BudgetFonds { get; set; }
        public Nullable<double> RequiredResource { get; set; }
        public string AppNumber { get; set; }
        public string RealtermUnit { get; set; }
        public string RealtermVolume { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string authorlogin { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual MAP_DIC_Status MAP_DIC_Status { get; set; }
        public virtual ICollection<MAP_ApplicationEvent> MAP_ApplicationEvent { get; set; }
        public virtual ICollection<MAP_ApplicationHistory> MAP_ApplicationHistory { get; set; }
        public virtual ICollection<MAP_ApplicationProduct> MAP_ApplicationProduct { get; set; }
        public virtual ICollection<MAP_Project> MAP_Project { get; set; }
    }
}
