//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RST_ReportReestr
    {
        public RST_ReportReestr()
        {
            this.RST_ReestrReportHistory = new HashSet<RST_ReestrReportHistory>();
            this.rst_reportreestroked = new HashSet<rst_reportreestroked>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ReportId { get; set; }
        public Nullable<long> ReestrId { get; set; }
        public string Address { get; set; }
        public string BINIIN { get; set; }
        public string OwnerName { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> Oblast { get; set; }
        public Nullable<long> ReasonId { get; set; }
        public string IDK { get; set; }
        public string Note { get; set; }
        public Nullable<long> Editor { get; set; }
        public Nullable<long> FormId { get; set; }
        public Nullable<long> Expectant { get; set; }
        public bool IsExcluded { get; set; }
        public Nullable<long> temp_id { get; set; }
        public string usrfirstname { get; set; }
        public string usrlastname { get; set; }
        public string usrsecondname { get; set; }
        public string usrjuridicalname { get; set; }
        public string usrpost { get; set; }
        public string usrmobile { get; set; }
        public string usrworkphone { get; set; }
        public string usrinternalphone { get; set; }
        public string usraddress { get; set; }
        public Nullable<bool> usriscvazy { get; set; }
        public string usrresponcefio { get; set; }
        public string usrresponcepost { get; set; }
        public Nullable<long> usroblast { get; set; }
        public Nullable<long> usrregion { get; set; }
        public Nullable<long> usrsubregion { get; set; }
        public Nullable<long> usrvillage { get; set; }
        public Nullable<long> usrtypeapplicationid { get; set; }
        public Nullable<long> usrokedid { get; set; }
        public Nullable<int> usrfscode { get; set; }
        public string usridk { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public string usremail { get; set; }
    
        public virtual DIC_Kato DIC_Kato { get; set; }
        public virtual DIC_Kato DIC_Kato1 { get; set; }
        public virtual DIC_Kato DIC_Kato2 { get; set; }
        public virtual DIC_Kato DIC_Kato3 { get; set; }
        public virtual DIC_Kato DIC_Kato4 { get; set; }
        public virtual DIC_OKED DIC_OKED { get; set; }
        public virtual DIC_TypeApplication DIC_TypeApplication { get; set; }
        public virtual RST_DIC_Reason RST_DIC_Reason { get; set; }
        public virtual RST_DIC_Reason RST_DIC_Reason1 { get; set; }
        public virtual RST_DIC_Status RST_DIC_Status { get; set; }
        public virtual RST_Reestr RST_Reestr { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
        public virtual RST_Report RST_Report { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual SUB_Form SUB_Form { get; set; }
        public virtual ICollection<rst_reportreestroked> rst_reportreestroked { get; set; }
    }
}
