//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rst_reportreestroked
    {
        public long id { get; set; }
        public long reportreestrid { get; set; }
        public long okedid { get; set; }
    
        public virtual DIC_OKED DIC_OKED { get; set; }
        public virtual RST_ReportReestr RST_ReportReestr { get; set; }
    }
}
