//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RST_DIC_Reason
    {
        public RST_DIC_Reason()
        {
            this.RST_Reestr = new HashSet<RST_Reestr>();
            this.RST_ReestrHistory = new HashSet<RST_ReestrHistory>();
            this.RST_ReestrReportHistory = new HashSet<RST_ReestrReportHistory>();
            this.RST_ReportReestr = new HashSet<RST_ReportReestr>();
            this.RST_ReestrReportHistory1 = new HashSet<RST_ReestrReportHistory>();
            this.RST_ReportReestr1 = new HashSet<RST_ReportReestr>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsExcluded { get; set; }
    
        public virtual ICollection<RST_Reestr> RST_Reestr { get; set; }
        public virtual ICollection<RST_ReestrHistory> RST_ReestrHistory { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory1 { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr1 { get; set; }
    }
}
