//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RST_Application
    {
        public RST_Application()
        {
            this.RST_Reestr = new HashSet<RST_Reestr>();
            this.RST_ReestrReportHistory = new HashSet<RST_ReestrReportHistory>();
        }
    
        public long Id { get; set; }
        public int ReportYear { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> Oblast { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual DIC_Kato DIC_Kato { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<RST_Reestr> RST_Reestr { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
    }
}
