//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rst_obl_control
    {
        public int id { get; set; }
        public long sec_user_id { get; set; }
        public long dic_kato_id { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual DIC_Kato DIC_Kato { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
