//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RST_Reestr
    {
        public RST_Reestr()
        {
            this.RST_ReestrHistory = new HashSet<RST_ReestrHistory>();
            this.RST_ReportReestr = new HashSet<RST_ReportReestr>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public string KadastNumber { get; set; }
        public string ObjectName { get; set; }
        public string Address { get; set; }
        public string BINIIN { get; set; }
        public string OwnerName { get; set; }
        public Nullable<long> ApplicationId { get; set; }
        public Nullable<long> StatusId { get; set; }
        public string Note { get; set; }
        public Nullable<long> ReasonId { get; set; }
        public string IDK { get; set; }
    
        public virtual RST_Application RST_Application { get; set; }
        public virtual RST_DIC_Reason RST_DIC_Reason { get; set; }
        public virtual RST_DIC_Status RST_DIC_Status { get; set; }
        public virtual ICollection<RST_ReestrHistory> RST_ReestrHistory { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr { get; set; }
    }
}
