//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_RightPermission
    {
        public SEC_RightPermission()
        {
            this.SEC_RightPermission1 = new HashSet<SEC_RightPermission>();
            this.SEC_RolePermission = new HashSet<SEC_RolePermission>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<SEC_RightPermission> SEC_RightPermission1 { get; set; }
        public virtual SEC_RightPermission SEC_RightPermission2 { get; set; }
        public virtual ICollection<SEC_RolePermission> SEC_RolePermission { get; set; }
    }
}
