//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_JurEvent
    {
        public long Id { get; set; }
        public string Event { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Author { get; set; }
        public string ClassName { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> EventTypeId { get; set; }
        public Nullable<long> ObjId { get; set; }
    
        public virtual SEC_DIC_EventType SEC_DIC_EventType { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
