//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_User
    {
        public SEC_User()
        {
            this.EAUDIT_Preamble = new HashSet<EAUDIT_Preamble>();
            this.EAUDIT_Preamble1 = new HashSet<EAUDIT_Preamble>();
            this.EAUDIT_Preamble2 = new HashSet<EAUDIT_Preamble>();
            this.ESCO_DIC_ProductKind = new HashSet<ESCO_DIC_ProductKind>();
            this.MAP_Application = new HashSet<MAP_Application>();
            this.MAP_Application1 = new HashSet<MAP_Application>();
            this.MAP_ApplicationHistory = new HashSet<MAP_ApplicationHistory>();
            this.MAP_FormEE2 = new HashSet<MAP_FormEE2>();
            this.MAP_Project = new HashSet<MAP_Project>();
            this.MAP_Project1 = new HashSet<MAP_Project>();
            this.RST_Application = new HashSet<RST_Application>();
            this.RST_Executed = new HashSet<RST_Executed>();
            this.rst_obl_control = new HashSet<rst_obl_control>();
            this.RST_ReestrHistory = new HashSet<RST_ReestrHistory>();
            this.RST_ReestrReportHistory = new HashSet<RST_ReestrReportHistory>();
            this.RST_ReestrReportHistory1 = new HashSet<RST_ReestrReportHistory>();
            this.RST_Report = new HashSet<RST_Report>();
            this.RST_ReportReestr = new HashSet<RST_ReportReestr>();
            this.RST_ReportReestr1 = new HashSet<RST_ReportReestr>();
            this.SEC_JurEvent = new HashSet<SEC_JurEvent>();
            this.SEC_UserKind = new HashSet<SEC_UserKind>();
            this.SEC_UserOked = new HashSet<SEC_UserOked>();
            this.SUB_ActionComRecord = new HashSet<SUB_ActionComRecord>();
            this.SUB_ActionHistory = new HashSet<SUB_ActionHistory>();
            this.SUB_ActionPlan = new HashSet<SUB_ActionPlan>();
            this.SUB_ActionPlan1 = new HashSet<SUB_ActionPlan>();
            this.SUB_Form = new HashSet<SUB_Form>();
            this.SUB_Form1 = new HashSet<SUB_Form>();
            this.SUB_FormComRecord = new HashSet<SUB_FormComRecord>();
            this.SUB_FormHistory = new HashSet<SUB_FormHistory>();
            this.SEC_UserHistory = new HashSet<SEC_UserHistory>();
            this.SUB_ActionRecordHistory = new HashSet<SUB_ActionRecordHistory>();
            this.SUB_DIC_Event = new HashSet<SUB_DIC_Event>();
            this.SUB_FormRecordHistory = new HashSet<SUB_FormRecordHistory>();
        }
    
        public long Id { get; set; }
        public string Login { get; set; }
        public string Pwd { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string JuridicalName { get; set; }
        public string Post { get; set; }
        public string BINIIN { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string WorkPhone { get; set; }
        public string InternalPhone { get; set; }
        public bool IsGuest { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<long> OrganizationId { get; set; }
        public Nullable<long> DeparmentId { get; set; }
        public Nullable<long> RolesId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Address { get; set; }
        public bool IsCvazy { get; set; }
        public string ResponceFIO { get; set; }
        public string ResponcePost { get; set; }
        public Nullable<long> Oblast { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<long> SubRegion { get; set; }
        public Nullable<long> Village { get; set; }
        public long TypeApplicationId { get; set; }
        public bool IsHaveGES { get; set; }
        public string IDK { get; set; }
        public Nullable<long> OkedId { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Certificate { get; set; }
        public string BankRequisites { get; set; }
        public string FactAddress { get; set; }
        public string urlSite { get; set; }
        public Nullable<long> FactOblast { get; set; }
        public Nullable<long> FactRegion { get; set; }
        public Nullable<long> FactSubRegion { get; set; }
        public Nullable<long> FactVillage { get; set; }
        public Nullable<int> FSCode { get; set; }
        public string Note { get; set; }
        public string BIN_IDK { get; set; }
        public string BIN_DEL { get; set; }
        public Nullable<long> BIN_Id { get; set; }
        public Nullable<bool> is_obl_control { get; set; }
        public Nullable<bool> ger_wo_ecp { get; set; }
    
        public virtual DIC_Department DIC_Department { get; set; }
        public virtual DIC_Kato DIC_Kato { get; set; }
        public virtual DIC_Kato DIC_Kato1 { get; set; }
        public virtual DIC_Kato DIC_Kato2 { get; set; }
        public virtual DIC_Kato DIC_Kato3 { get; set; }
        public virtual DIC_OKED DIC_OKED { get; set; }
        public virtual DIC_Organization DIC_Organization { get; set; }
        public virtual DIC_TypeApplication DIC_TypeApplication { get; set; }
        public virtual ICollection<EAUDIT_Preamble> EAUDIT_Preamble { get; set; }
        public virtual ICollection<EAUDIT_Preamble> EAUDIT_Preamble1 { get; set; }
        public virtual ICollection<EAUDIT_Preamble> EAUDIT_Preamble2 { get; set; }
        public virtual ICollection<ESCO_DIC_ProductKind> ESCO_DIC_ProductKind { get; set; }
        public virtual ICollection<MAP_Application> MAP_Application { get; set; }
        public virtual ICollection<MAP_Application> MAP_Application1 { get; set; }
        public virtual ICollection<MAP_ApplicationHistory> MAP_ApplicationHistory { get; set; }
        public virtual ICollection<MAP_FormEE2> MAP_FormEE2 { get; set; }
        public virtual ICollection<MAP_Project> MAP_Project { get; set; }
        public virtual ICollection<MAP_Project> MAP_Project1 { get; set; }
        public virtual ICollection<RST_Application> RST_Application { get; set; }
        public virtual ICollection<RST_Executed> RST_Executed { get; set; }
        public virtual ICollection<rst_obl_control> rst_obl_control { get; set; }
        public virtual ICollection<RST_ReestrHistory> RST_ReestrHistory { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory { get; set; }
        public virtual ICollection<RST_ReestrReportHistory> RST_ReestrReportHistory1 { get; set; }
        public virtual ICollection<RST_Report> RST_Report { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr { get; set; }
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr1 { get; set; }
        public virtual ICollection<SEC_JurEvent> SEC_JurEvent { get; set; }
        public virtual SEC_Roles SEC_Roles { get; set; }
        public virtual ICollection<SEC_UserKind> SEC_UserKind { get; set; }
        public virtual ICollection<SEC_UserOked> SEC_UserOked { get; set; }
        public virtual ICollection<SUB_ActionComRecord> SUB_ActionComRecord { get; set; }
        public virtual ICollection<SUB_ActionHistory> SUB_ActionHistory { get; set; }
        public virtual ICollection<SUB_ActionPlan> SUB_ActionPlan { get; set; }
        public virtual ICollection<SUB_ActionPlan> SUB_ActionPlan1 { get; set; }
        public virtual ICollection<SUB_Form> SUB_Form { get; set; }
        public virtual ICollection<SUB_Form> SUB_Form1 { get; set; }
        public virtual ICollection<SUB_FormComRecord> SUB_FormComRecord { get; set; }
        public virtual ICollection<SUB_FormHistory> SUB_FormHistory { get; set; }
        public virtual ICollection<SEC_UserHistory> SEC_UserHistory { get; set; }
        public virtual ICollection<SUB_ActionRecordHistory> SUB_ActionRecordHistory { get; set; }
        public virtual ICollection<SUB_DIC_Event> SUB_DIC_Event { get; set; }
        public virtual ICollection<SUB_FormRecordHistory> SUB_FormRecordHistory { get; set; }
    }
}
