//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_RolePermission
    {
        public long Id { get; set; }
        public Nullable<long> RolesId { get; set; }
        public Nullable<long> RightPermissionId { get; set; }
        public bool IS_EDIT { get; set; }
    
        public virtual SEC_RightPermission SEC_RightPermission { get; set; }
        public virtual SEC_Roles SEC_Roles { get; set; }
    }
}
