//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_DIC_Status
    {
        public SUB_DIC_Status()
        {
            this.SUB_ActionHistory = new HashSet<SUB_ActionHistory>();
            this.SUB_ActionPlan = new HashSet<SUB_ActionPlan>();
            this.SUB_Form = new HashSet<SUB_Form>();
            this.SUB_FormHistory = new HashSet<SUB_FormHistory>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SUB_ActionHistory> SUB_ActionHistory { get; set; }
        public virtual ICollection<SUB_ActionPlan> SUB_ActionPlan { get; set; }
        public virtual ICollection<SUB_Form> SUB_Form { get; set; }
        public virtual ICollection<SUB_FormHistory> SUB_FormHistory { get; set; }
    }
}
