//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_dic_energyindicator
    {
        public sub_dic_energyindicator()
        {
            this.SUB_Form5Record = new HashSet<SUB_Form5Record>();
        }
    
        public long id { get; set; }
        public string namekz { get; set; }
        public string nameru { get; set; }
        public string unitnamekz { get; set; }
        public string unitnameru { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<bool> forgu { get; set; }
    
        public virtual ICollection<SUB_Form5Record> SUB_Form5Record { get; set; }
    }
}
