//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_Form
    {
        public SUB_Form()
        {
            this.RST_ReportReestr = new HashSet<RST_ReportReestr>();
            this.SUB_Form2Record = new HashSet<SUB_Form2Record>();
            this.SUB_Form3Record = new HashSet<SUB_Form3Record>();
            this.SUB_Form4Record = new HashSet<SUB_Form4Record>();
            this.SUB_Form5Record = new HashSet<SUB_Form5Record>();
            this.SUB_Form6Record = new HashSet<SUB_Form6Record>();
            this.SUB_FormComment = new HashSet<SUB_FormComment>();
            this.SUB_FormHistory = new HashSet<SUB_FormHistory>();
            this.SUB_FormTab1 = new HashSet<SUB_FormTab1>();
            this.SUB_FormTab2 = new HashSet<SUB_FormTab2>();
            this.SUB_FormTab3 = new HashSet<SUB_FormTab3>();
            this.SUB_Form2Gu = new HashSet<SUB_Form2Gu>();
            this.SUB_Form3aGuRecord1 = new HashSet<SUB_Form3aGuRecord1>();
            this.SUB_Form3aGuRecord2 = new HashSet<SUB_Form3aGuRecord2>();
            this.SUB_Form3aGuRecord3 = new HashSet<SUB_Form3aGuRecord3>();
            this.SUB_Form3Gu = new HashSet<SUB_Form3Gu>();
            this.SUB_Form3GuRecord = new HashSet<SUB_Form3GuRecord>();
            this.SUB_FormGuLightingInfo = new HashSet<SUB_FormGuLightingInfo>();
            this.SUB_FormKadastr = new HashSet<SUB_FormKadastr>();
            this.SUB_FormRecordHistory = new HashSet<SUB_FormRecordHistory>();
        }
    
        public long Id { get; set; }
        public int ReportYear { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> Editor { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<System.DateTime> DesignDate { get; set; }
        public string DesignNote { get; set; }
        public bool IsPlan { get; set; }
        public Nullable<int> BeginPlanYear { get; set; }
        public Nullable<int> EndPlanYear { get; set; }
        public bool IsBack { get; set; }
        public bool IsConfirmPlan { get; set; }
        public Nullable<long> temp_id { get; set; }
        public bool IsNotEvents { get; set; }
        public Nullable<bool> IsEnergyManagementSystem { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public Nullable<bool> IsRent { get; set; }
    
        public virtual ICollection<RST_ReportReestr> RST_ReportReestr { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual SUB_DIC_Status SUB_DIC_Status { get; set; }
        public virtual ICollection<SUB_Form2Record> SUB_Form2Record { get; set; }
        public virtual ICollection<SUB_Form3Record> SUB_Form3Record { get; set; }
        public virtual ICollection<SUB_Form4Record> SUB_Form4Record { get; set; }
        public virtual ICollection<SUB_Form5Record> SUB_Form5Record { get; set; }
        public virtual ICollection<SUB_Form6Record> SUB_Form6Record { get; set; }
        public virtual ICollection<SUB_FormComment> SUB_FormComment { get; set; }
        public virtual ICollection<SUB_FormHistory> SUB_FormHistory { get; set; }
        public virtual ICollection<SUB_FormTab1> SUB_FormTab1 { get; set; }
        public virtual ICollection<SUB_FormTab2> SUB_FormTab2 { get; set; }
        public virtual ICollection<SUB_FormTab3> SUB_FormTab3 { get; set; }
        public virtual ICollection<SUB_Form2Gu> SUB_Form2Gu { get; set; }
        public virtual ICollection<SUB_Form3aGuRecord1> SUB_Form3aGuRecord1 { get; set; }
        public virtual ICollection<SUB_Form3aGuRecord2> SUB_Form3aGuRecord2 { get; set; }
        public virtual ICollection<SUB_Form3aGuRecord3> SUB_Form3aGuRecord3 { get; set; }
        public virtual ICollection<SUB_Form3Gu> SUB_Form3Gu { get; set; }
        public virtual ICollection<SUB_Form3GuRecord> SUB_Form3GuRecord { get; set; }
        public virtual ICollection<SUB_FormGuLightingInfo> SUB_FormGuLightingInfo { get; set; }
        public virtual ICollection<SUB_FormKadastr> SUB_FormKadastr { get; set; }
        public virtual ICollection<SUB_FormRecordHistory> SUB_FormRecordHistory { get; set; }
    }
}
