//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_ActionRecordHistory
    {
        public long Id { get; set; }
        public Nullable<long> ActionId { get; set; }
        public string TabName { get; set; }
        public string ClassName { get; set; }
        public string FieldName { get; set; }
        public string TypeValue { get; set; }
        public string FieldValue { get; set; }
        public Nullable<long> RecordId { get; set; }
        public string Unique { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual SUB_ActionPlan SUB_ActionPlan { get; set; }
    }
}
