//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_FormComRecord
    {
        public long Id { get; set; }
        public Nullable<long> CommentId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Note { get; set; }
        public string ValueField { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual SUB_FormComment SUB_FormComment { get; set; }
    }
}
