//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_DIC_TypeCounter
    {
        public SUB_DIC_TypeCounter()
        {
            this.SUB_Form4Record = new HashSet<SUB_Form4Record>();
            this.SUB_Form6Record = new HashSet<SUB_Form6Record>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public Nullable<int> PosIndex { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SUB_Form4Record> SUB_Form4Record { get; set; }
        public virtual ICollection<SUB_Form6Record> SUB_Form6Record { get; set; }
    }
}
