//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_ActionComment
    {
        public SUB_ActionComment()
        {
            this.SUB_ActionComRecord = new HashSet<SUB_ActionComRecord>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ActionId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RowIndex { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public bool IsError { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> Editor { get; set; }
        public bool IsDeleted { get; set; }
        public string Unique { get; set; }
    
        public virtual SUB_ActionPlan SUB_ActionPlan { get; set; }
        public virtual ICollection<SUB_ActionComRecord> SUB_ActionComRecord { get; set; }
    }
}
