//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_Form3aGuRecord1
    {
        public long Id { get; set; }
        public long FormId { get; set; }
        public Nullable<int> DicId { get; set; }
        public Nullable<int> CountOfHeatingSources { get; set; }
        public Nullable<int> CoefficientOfPerformance { get; set; }
        public Nullable<double> PowerOfHeatingSources { get; set; }
        public Nullable<int> YearOfCommissioning { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> KindIndex { get; set; }
    
        public virtual DIC_GU DIC_GU { get; set; }
        public virtual SUB_Form SUB_Form { get; set; }
    }
}
