//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_ActionTab1
    {
        public long Id { get; set; }
        public Nullable<long> ActionId { get; set; }
        public Nullable<long> KindId { get; set; }
        public string Code { get; set; }
        public string Events { get; set; }
        public string Year1 { get; set; }
        public string Year2 { get; set; }
        public string Year3 { get; set; }
        public string Year4 { get; set; }
        public string Year5 { get; set; }
        public Nullable<double> Expend1 { get; set; }
        public Nullable<double> Expend2 { get; set; }
        public Nullable<double> Expend3 { get; set; }
        public Nullable<double> Expend4 { get; set; }
        public Nullable<double> Expend5 { get; set; }
        public string Note { get; set; }
        public Nullable<long> EventId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UnitName { get; set; }
        public Nullable<float> PaybackPeriod { get; set; }
    
        public virtual SUB_ActionPlan SUB_ActionPlan { get; set; }
        public virtual SUB_DIC_KindTabOne SUB_DIC_KindTabOne { get; set; }
        public virtual SUB_DIC_Event SUB_DIC_Event { get; set; }
    }
}
