//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_FormComment
    {
        public SUB_FormComment()
        {
            this.SUB_FormComRecord = new HashSet<SUB_FormComRecord>();
        }
    
        public long Id { get; set; }
        public Nullable<long> FormId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RowIndex { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
        public bool IsError { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> Editor { get; set; }
        public bool IsDeleted { get; set; }
        public string Unique { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
    
        public virtual SUB_Form SUB_Form { get; set; }
        public virtual ICollection<SUB_FormComRecord> SUB_FormComRecord { get; set; }
    }
}
