//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_Form3Gu
    {
        public int Id { get; set; }
        public long FormId { get; set; }
        public string YearOfConstruction { get; set; }
        public Nullable<short> AutomateItem { get; set; }
        public Nullable<double> TotalAreaOfBuilding { get; set; }
        public Nullable<double> HeatedAreaOfBuilding { get; set; }
        public Nullable<int> IndependentHeating { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public Nullable<long> authorid { get; set; }
        public string authorlogin { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<int> CentralHeating { get; set; }
    
        public virtual SUB_Form SUB_Form { get; set; }
    }
}
