//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_ActionTab2
    {
        public long Id { get; set; }
        public Nullable<long> ActionId { get; set; }
        public Nullable<long> KindId { get; set; }
        public Nullable<double> Volume1 { get; set; }
        public Nullable<double> Volume2 { get; set; }
        public Nullable<double> Volume3 { get; set; }
        public Nullable<double> Volume4 { get; set; }
        public Nullable<double> Volume5 { get; set; }
        public Nullable<double> Expend1 { get; set; }
        public Nullable<double> Expend2 { get; set; }
        public Nullable<double> Expend3 { get; set; }
        public Nullable<double> Expend4 { get; set; }
        public Nullable<double> Expend5 { get; set; }
        public string Possible { get; set; }
        public string Note { get; set; }
        public string UnitName { get; set; }
        public Nullable<float> Potential { get; set; }
    
        public virtual SUB_ActionPlan SUB_ActionPlan { get; set; }
        public virtual SUB_DIC_KindTabTwo SUB_DIC_KindTabTwo { get; set; }
    }
}
