//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aisger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_DIC_NormEnergy
    {
        public SUB_DIC_NormEnergy()
        {
            this.SUB_Form5Record = new HashSet<SUB_Form5Record>();
            this.SUB_DIC_NormEnergy1 = new HashSet<SUB_DIC_NormEnergy>();
        }
    
        public long Id { get; set; }
        public string NameRu { get; set; }
        public string UnitName { get; set; }
        public string Rate { get; set; }
        public Nullable<long> refParent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SUB_Form5Record> SUB_Form5Record { get; set; }
        public virtual ICollection<SUB_DIC_NormEnergy> SUB_DIC_NormEnergy1 { get; set; }
        public virtual SUB_DIC_NormEnergy SUB_DIC_NormEnergy2 { get; set; }
    }
}
